version: '3.8'

services:
  # --- DATABASE ---
  postgres:
    image: postgres:15
    container_name: bank_postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: bank_fraud_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      retries: 5

  # --- Adminer ---
  adminer:
    image: adminer
    container_name: bank_db_viewer
    restart: always
    ports:
      - "8081:8080" 
    networks:
      - bank_network
    depends_on:
      - postgres

  # --- AIRFLOW WEBSERVER ---
  airflow-webserver:
    image: apache/airflow:2.7.1
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin_password@postgres/bank_fraud_db
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin_password@postgres/bank_fraud_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False 
      - AIRFLOW_ADMIN_USER=admin
      - AIRFLOW_ADMIN_PASSWORD=admin
    volumes:
      - ./dags:/opt/airflow/dags 
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - bank_network
    depends_on:
      postgres:
        condition: service_healthy

  # --- AIRFLOW SCHEDULER ---
  airflow-scheduler:
    image: apache/airflow:2.7.1
    container_name: airflow_scheduler
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin_password@postgres/bank_fraud_db
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin_password@postgres/bank_fraud_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - bank_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  bank_network:
    driver: bridge