version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bank_postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: bank_fraud_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank_network

  adminer:
    image: adminer
    container_name: bank_db_viewer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - bank_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  bank_network:
    driver: bridge